version: "3"
name: strapi-jamstack-frontend

services:
  nextjs:
    env_file: .env.production
    container_name: nextjs 
   # network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'